# Generated by Django 4.0.4 on 2023-01-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todollist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TimeField()),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
