# Generated by Django 4.0.4 on 2023-01-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todollist',
            name='data',
            field=models.DateField(),
        ),
    ]
