# Generated by Django 4.0.4 on 2023-01-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_todollist_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todollist',
            old_name='data',
            new_name='date',
        ),
    ]
